In [7]:
import torch

In [8]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [9]:
scalar.ndim

0

In [10]:
# get tensor back as python int
scalar.item()

7

In [11]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [12]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([2])

In [14]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [17]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape

torch.Size([1, 3, 3])

In [20]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

# Random tensors

In [21]:
# create a random sensor of size  ( 3, 4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1074, 0.9661, 0.7646, 0.1345],
        [0.7905, 0.7656, 0.7355, 0.0978],
        [0.9389, 0.9028, 0.6646, 0.0236]])

In [31]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(448, 448, 3)) # height. width, color channel (RGB) 
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([448, 448, 3]), 3)

In [32]:
import cv2

In [33]:
image = random_image_size_tensor.numpy()
cv2.imshow('image window', image)
# add wait key. window waits until user presses a key
cv2.waitKey(0)
# and finally destroy/close all open windows
cv2.destroyAllWindows()

In [35]:
random_image_size_tensor.dtype

torch.float32

In [42]:
# Torch Range
torch.arange(1, 11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Tensor Datatypes
Note: Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [47]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [48]:
float_32_tensor.dtype

torch.float32

In [49]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [50]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [51]:
# create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9556, 0.1531, 0.2602, 0.8092],
        [0.8930, 0.9089, 0.4657, 0.0845],
        [0.5513, 0.8569, 0.5537, 0.0289]])

In [52]:
# find out details about some tensor
some_tensor

tensor([[0.9556, 0.1531, 0.2602, 0.8092],
        [0.8930, 0.9089, 0.4657, 0.0845],
        [0.5513, 0.8569, 0.5537, 0.0289]])

In [53]:
some_tensor.dtype

torch.float32

In [54]:
some_tensor.shape

torch.Size([3, 4])

In [55]:
some_tensor.device

device(type='cpu')

### Matrix multiplication
### 2 main ways
 1) Element-wise
 2) Matrix mutiplication (dot product)


In [5]:
import torch

# Element-wise
tensor = torch.rand(128, 128)
tensor

tensor([[0.3436, 0.5993, 0.2849,  ..., 0.7932, 0.9298, 0.0403],
        [0.9100, 0.8846, 0.2436,  ..., 0.5748, 0.9440, 0.2586],
        [0.3601, 0.1968, 0.7553,  ..., 0.0840, 0.0820, 0.1423],
        ...,
        [0.7169, 0.3978, 0.4194,  ..., 0.1400, 0.6263, 0.0896],
        [0.4781, 0.5595, 0.7772,  ..., 0.0189, 0.3178, 0.9328],
        [0.2928, 0.0122, 0.4547,  ..., 0.3798, 0.9843, 0.9778]])

In [6]:
tensor * tensor

tensor([[1.1804e-01, 3.5920e-01, 8.1191e-02,  ..., 6.2915e-01, 8.6462e-01,
         1.6240e-03],
        [8.2819e-01, 7.8258e-01, 5.9347e-02,  ..., 3.3039e-01, 8.9120e-01,
         6.6883e-02],
        [1.2968e-01, 3.8731e-02, 5.7050e-01,  ..., 7.0561e-03, 6.7309e-03,
         2.0262e-02],
        ...,
        [5.1396e-01, 1.5827e-01, 1.7589e-01,  ..., 1.9597e-02, 3.9220e-01,
         8.0194e-03],
        [2.2861e-01, 3.1301e-01, 6.0408e-01,  ..., 3.5831e-04, 1.0099e-01,
         8.7004e-01],
        [8.5747e-02, 1.4953e-04, 2.0675e-01,  ..., 1.4427e-01, 9.6880e-01,
         9.5612e-01]])

In [7]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor([[33.4676, 32.4152, 31.8294,  ..., 31.7312, 34.6029, 33.4739],
        [31.8206, 31.2945, 31.8782,  ..., 30.9338, 34.6718, 33.5638],
        [31.8015, 30.1163, 32.2659,  ..., 33.2020, 34.9015, 33.9448],
        ...,
        [33.5360, 33.3367, 33.4309,  ..., 33.8530, 38.0825, 35.0913],
        [29.5721, 29.9796, 29.2267,  ..., 31.3010, 31.8694, 33.1433],
        [33.8143, 29.8673, 32.3483,  ..., 32.3277, 35.3931, 34.2305]])

In [8]:
%%time
tensor @ tensor

CPU times: total: 0 ns
Wall time: 998 μs


tensor([[33.4676, 32.4152, 31.8294,  ..., 31.7312, 34.6029, 33.4739],
        [31.8206, 31.2945, 31.8782,  ..., 30.9338, 34.6718, 33.5638],
        [31.8015, 30.1163, 32.2659,  ..., 33.2020, 34.9015, 33.9448],
        ...,
        [33.5360, 33.3367, 33.4309,  ..., 33.8530, 38.0825, 35.0913],
        [29.5721, 29.9796, 29.2267,  ..., 31.3010, 31.8694, 33.1433],
        [33.8143, 29.8673, 32.3483,  ..., 32.3277, 35.3931, 34.2305]])

# Tensor aggregation

In [12]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [20]:
# find the min
torch.min(x), x.min()

(tensor(0.), tensor(0.))

In [21]:
# find the max
torch.max(x), x.max()

(tensor(90.), tensor(90.))

In [22]:
# find the mean
x = x.type(torch.float32)

torch.mean(x), x.mean()

(tensor(45.), tensor(45.))

# Reshaping, Stacking, Squeezing, Unsqueezing

In [23]:
import torch
X = torch.arange(1., 10.)
X, X.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [42]:
# Add an extra dimension
X_reshaped = X.reshape(1,9)
X_reshaped, X_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [28]:
# Change the view
z = X.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [30]:
# Changin z changes x
z[:, 0] = 5
z, X

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [35]:
# Stack tensors on top of each other
X_stacked = torch.stack([X, X, X, X], dim=0)
X_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [46]:
# torch.squeeze() ---> removes all single dimensions from a target tensor
X_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [47]:
X_reshaped.shape

torch.Size([1, 9])

In [49]:
X_squeezed = X_reshaped.squeeze()
X_squeezed

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [50]:
X_squeezed.shape

torch.Size([9])

In [51]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
X_squeezed

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [57]:
X_unsqueezed = X_squeezed.unsqueeze(dim=0)
X_unsqueezed

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [58]:
X_unsqueezed.shape

torch.Size([1, 9])

In [59]:
X_unsqueezed = X_squeezed.unsqueeze(dim=1)
X_unsqueezed

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [60]:
X_unsqueezed.shape

torch.Size([9, 1])

In [65]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # height, width, color_channels
print(f"x_original shape: {x_original.shape}")

# Permute
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0-->1, 1-->2, 2-->0
print(f"x_permuted shape: {x_permuted.shape}")

x_original shape: torch.Size([224, 224, 3])
x_permuted shape: torch.Size([3, 224, 224])


In [66]:
x_original[0,0,0] = 1234
x_original[0,0,0], x_permuted[0,0,0]

(tensor(1234.), tensor(1234.))

# Indexing (Selecting data from tensors)

In [68]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [80]:
x[:,:, 2]

tensor([[3, 6, 9]])

# PyTorch tensors & NumPy

In [81]:
# Tensor to NumPy
tensor = torch = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [82]:
# Change the tensor, what happens to 'numpy_tensor'?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [86]:
import numpy as np
import torch
array = np.ones(10)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64))

In [88]:
torch.cuda.device_count()

1

# Exercises

In [93]:
# 2)
import torch
tensor = torch.rand(7,7)
tensor

tensor([[0.4045, 0.3582, 0.0576, 0.1959, 0.7658, 0.0705, 0.8319],
        [0.5488, 0.3972, 0.9785, 0.6996, 0.6964, 0.5233, 0.9496],
        [0.3294, 0.0544, 0.9630, 0.0460, 0.1122, 0.2327, 0.1112],
        [0.0930, 0.7774, 0.8481, 0.6085, 0.6027, 0.9461, 0.1521],
        [0.1086, 0.3052, 0.8233, 0.3640, 0.1571, 0.2769, 0.2250],
        [0.1306, 0.3625, 0.7324, 0.6653, 0.6755, 0.5623, 0.3409],
        [0.9467, 0.8849, 0.2476, 0.2160, 0.3667, 0.5850, 0.6880]])

In [94]:
tensor2 = torch.rand(1,7)
tensor2

tensor([[0.2991, 0.0276, 0.2080, 0.8745, 0.0343, 0.7843, 0.5722]])

In [110]:
# 3)
tensor @ tensor2.T

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [111]:
# 4) Reproducibility
import torch
torch.manual_seed(0)
tensor = torch.rand(7,7)
tensor

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [112]:
torch.manual_seed(0)
tensor2 = torch.rand(1,7)
tensor2

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])

In [113]:
tensor @ tensor2.T

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [122]:
# 5) GPU
torch.manual_seed(1234)
tenso1 = torch.rand(2, 3)

torch.manual_seed(1234)
tenso2 = torch.rand(2, 3)

In [128]:
tenso1

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])

In [126]:
gpu_tenso1 = tenso1.to('cuda')

In [127]:
gpu_tenso1

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')

In [129]:
gpu_tenso2 = tenso2.to('cuda')
gpu_tenso2

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')

In [130]:
gpu_tenso1.shape, gpu_tenso2.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [133]:
mm = gpu_tenso1 @ gpu_tenso2.T
mm

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

In [134]:
mm.min()

tensor(0.2161, device='cuda:0')

In [135]:
mm.max()

tensor(0.6287, device='cuda:0')

In [136]:
mm.mean()

tensor(0.3227, device='cuda:0')

In [137]:
mm.argmax()

tensor(3, device='cuda:0')

In [138]:
mm.argmin()

tensor(1, device='cuda:0')

In [150]:
torch.manual_seed(7)
random_tensor = torch.rand(1, 1, 1, 1, 10)
random_tensor, random_tensor.shape

(tensor([[[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
             0.3653, 0.8513]]]]]),
 torch.Size([1, 1, 1, 1, 10]))

In [152]:
squeezed_tenso = random_tensor.squeeze()
squeezed_tenso, squeezed_tenso.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))